import { defineConfig } from 'astro/config';
import { locales, defaultLocale } from './src/i18n/config';

// URL scheme matches churchbased.bible: English at /, every other locale at
// /{lang}/ — existing English URLs keep working unchanged. Content languages
// (the DCS catalog) live under /l/{code}/ so they never collide with these.
//
// Sitemaps are generated by src/pages/sitemap-*.xml.ts (an index plus one
// file each for marketing pages and language hubs) rather than
// @astrojs/sitemap, which cannot split files or add hubs with lastmod.
export default defineConfig({
  site: 'https://openbiblestories.org',
  devToolbar: { enabled: false },
  trailingSlash: 'always',

  // Keep the built HTML uncompressed so it stays diffable against the
  // original hand-written pages this site was migrated from.
  compressHTML: false,

  i18n: {
    defaultLocale,
    locales: locales.map((l) => l.code),
    routing: {
      prefixDefaultLocale: false,
    },
  },
});
